/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.carrito.views;

import ec.edu.ups.carrito.controllers.ProductoController;
import ec.edu.ups.carrito.dao.ProductoDAO;
import ec.edu.ups.carrito.dao.ProductoDAOMemoria;

/**
 *
 * @author User
 */
public class PrincipalView extends javax.swing.JFrame {
    private CrearProductoView crearProductoView;
    private ProductoController productoController;
    private BuscarProductoView buscarProductoView;
    private EliminarProductoView eliminarProductoView;
    private ActualizarProductoView actualizarProductoView;
    private ProductoDAO productoDAO;

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        crearProductoView = new CrearProductoView();
        productoDAO = new ProductoDAOMemoria();
        productoController = new ProductoController(crearProductoView, productoDAO, 
                actualizarProductoView, eliminarProductoView, buscarProductoView);
        actualizarProductoView = new ActualizarProductoView();
        buscarProductoView = new BuscarProductoView();
        eliminarProductoView = new EliminarProductoView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        productoMenu = new javax.swing.JMenu();
        crearProductoMenutem = new javax.swing.JMenuItem();
        buscarProductoMenuItem = new javax.swing.JMenuItem();
        eliminarProductoMenuItem = new javax.swing.JMenuItem();
        actualizarProductoMenuItem = new javax.swing.JMenuItem();
        carritoMenu = new javax.swing.JMenu();
        agregarProductoCarritoMenuItem = new javax.swing.JMenuItem();
        eliminarProductoCarritoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productoMenu.setMnemonic('f');
        productoMenu.setText("Productos");

        crearProductoMenutem.setMnemonic('o');
        crearProductoMenutem.setText("Crear");
        crearProductoMenutem.addActionListener(this::crearProductoMenutemActionPerformed);
        productoMenu.add(crearProductoMenutem);

        buscarProductoMenuItem.setMnemonic('s');
        buscarProductoMenuItem.setText("Buscar");
        buscarProductoMenuItem.addActionListener(this::buscarProductoMenuItemActionPerformed);
        productoMenu.add(buscarProductoMenuItem);

        eliminarProductoMenuItem.setMnemonic('a');
        eliminarProductoMenuItem.setText("Eliminar");
        eliminarProductoMenuItem.addActionListener(this::eliminarProductoMenuItemActionPerformed);
        productoMenu.add(eliminarProductoMenuItem);

        actualizarProductoMenuItem.setMnemonic('x');
        actualizarProductoMenuItem.setText("Actualizar");
        actualizarProductoMenuItem.addActionListener(this::actualizarProductoMenuItemActionPerformed);
        productoMenu.add(actualizarProductoMenuItem);

        menuBar.add(productoMenu);

        carritoMenu.setMnemonic('e');
        carritoMenu.setText("Carrito");

        agregarProductoCarritoMenuItem.setMnemonic('t');
        agregarProductoCarritoMenuItem.setText("Agregar");
        carritoMenu.add(agregarProductoCarritoMenuItem);

        eliminarProductoCarritoMenuItem.setMnemonic('y');
        eliminarProductoCarritoMenuItem.setText("Eliminar");
        carritoMenu.add(eliminarProductoCarritoMenuItem);

        menuBar.add(carritoMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProductoMenuItemActionPerformed
        if (!actualizarProductoView.isVisible()) {
            desktopPane.remove(actualizarProductoView);
            actualizarProductoView.setVisible(true);
            desktopPane.add(actualizarProductoView);
        }
    }//GEN-LAST:event_actualizarProductoMenuItemActionPerformed

    private void crearProductoMenutemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoMenutemActionPerformed
        if(!crearProductoView.isVisible()){
            desktopPane.remove(crearProductoView);
            crearProductoView.setVisible(true);
            desktopPane.add(crearProductoView);
        }
    }//GEN-LAST:event_crearProductoMenutemActionPerformed

    private void buscarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoMenuItemActionPerformed
        if (!buscarProductoView.isVisible()) {
            desktopPane.remove(buscarProductoView);
            buscarProductoView.setVisible(true);
            desktopPane.add(buscarProductoView);
        }
    }//GEN-LAST:event_buscarProductoMenuItemActionPerformed

    private void eliminarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoMenuItemActionPerformed
        if (!eliminarProductoView.isVisible()) {
            desktopPane.remove(eliminarProductoView);
            eliminarProductoView.setVisible(true);
            desktopPane.add(eliminarProductoView);
        }
    }//GEN-LAST:event_eliminarProductoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actualizarProductoMenuItem;
    private javax.swing.JMenuItem agregarProductoCarritoMenuItem;
    private javax.swing.JMenuItem buscarProductoMenuItem;
    private javax.swing.JMenu carritoMenu;
    private javax.swing.JMenuItem crearProductoMenutem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem eliminarProductoCarritoMenuItem;
    private javax.swing.JMenuItem eliminarProductoMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu productoMenu;
    // End of variables declaration//GEN-END:variables

}
