/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.carrito.views;

import ec.edu.ups.carrito.controllers.ProductoController;
import ec.edu.ups.carrito.dao.ProductoDAO;
import ec.edu.ups.carrito.dao.ProductoDAOMemoria;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author User
 */
public class PrincipalView extends javax.swing.JFrame {
    private CrearProductoView crearProductoView;
    private ProductoController productoController;
    private BuscarProductoView buscarProductoView;
    private EliminarProductoView eliminarProductoView;
    private ActualizarProductoView actualizarProductoView;
    private ListarProductosView listarProductosView;
    private ProductoDAO productoDAO;

    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.carrito.i18n.mensajes", locale);
        productoMenu.setText(bundle.getString("productoMenu"));
        crearProductoMenuItem.setText(bundle.getString("crearMenuItem"));
        buscarProductoMenuItem.setText(bundle.getString("buscarMenuItem"));
        eliminarProductoMenuItem.setText(bundle.getString("eliminarMenuItem"));
        actualizarProductoMenuItem.setText(bundle.getString("actualizarMenuItem"));       
        listarProductosMenuItem.setText(bundle.getString("listarMenuItem"));
        
        carritoMenu.setText(bundle.getString("carritoMenu"));
        agregarProductoCarritoMenuItem.setText(bundle.getString("agregarMenuItem"));
        eliminarProductoCarritoMenuItem.setText(bundle.getString("eliminarMenuItem"));
        idiomaMenu.setText(bundle.getString("idiomaMenuItem"));
        idiomaEspanolMenuItem.setText(bundle.getString("idiomaEspanolMenuItem"));
        idiomaInglesMenuItem.setText(bundle.getString("idiomaInglesMenuItem"));
        
    }
    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        
        crearProductoView = new CrearProductoView();
        productoDAO = new ProductoDAOMemoria();
        actualizarProductoView = new ActualizarProductoView();
        buscarProductoView = new BuscarProductoView();
        eliminarProductoView = new EliminarProductoView();
        listarProductosView = new ListarProductosView();
        productoController = new ProductoController(crearProductoView, productoDAO, 
                actualizarProductoView, eliminarProductoView, buscarProductoView, listarProductosView);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFondo = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        productoMenu = new javax.swing.JMenu();
        crearProductoMenuItem = new javax.swing.JMenuItem();
        buscarProductoMenuItem = new javax.swing.JMenuItem();
        eliminarProductoMenuItem = new javax.swing.JMenuItem();
        actualizarProductoMenuItem = new javax.swing.JMenuItem();
        listarProductosMenuItem = new javax.swing.JMenuItem();
        carritoMenu = new javax.swing.JMenu();
        agregarProductoCarritoMenuItem = new javax.swing.JMenuItem();
        eliminarProductoCarritoMenuItem = new javax.swing.JMenuItem();
        idiomaMenu = new javax.swing.JMenu();
        idiomaEspanolMenuItem = new javax.swing.JMenuItem();
        idiomaInglesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/carrito/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(lblFondo, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        productoMenu.setMnemonic('f');
        productoMenu.setText("Productos");

        crearProductoMenuItem.setMnemonic('o');
        crearProductoMenuItem.setText("Crear");
        crearProductoMenuItem.addActionListener(this::crearProductoMenuItemActionPerformed);
        productoMenu.add(crearProductoMenuItem);

        buscarProductoMenuItem.setMnemonic('s');
        buscarProductoMenuItem.setText("Buscar");
        buscarProductoMenuItem.addActionListener(this::buscarProductoMenuItemActionPerformed);
        productoMenu.add(buscarProductoMenuItem);

        eliminarProductoMenuItem.setMnemonic('a');
        eliminarProductoMenuItem.setText("Eliminar");
        eliminarProductoMenuItem.addActionListener(this::eliminarProductoMenuItemActionPerformed);
        productoMenu.add(eliminarProductoMenuItem);

        actualizarProductoMenuItem.setMnemonic('x');
        actualizarProductoMenuItem.setText("Actualizar");
        actualizarProductoMenuItem.addActionListener(this::actualizarProductoMenuItemActionPerformed);
        productoMenu.add(actualizarProductoMenuItem);

        listarProductosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, 0));
        listarProductosMenuItem.setText("Listar");
        listarProductosMenuItem.addActionListener(this::listarProductosMenuItemActionPerformed);
        productoMenu.add(listarProductosMenuItem);

        menuBar.add(productoMenu);

        carritoMenu.setMnemonic('e');
        carritoMenu.setText("Carrito");

        agregarProductoCarritoMenuItem.setMnemonic('t');
        agregarProductoCarritoMenuItem.setText("Agregar");
        carritoMenu.add(agregarProductoCarritoMenuItem);

        eliminarProductoCarritoMenuItem.setMnemonic('y');
        eliminarProductoCarritoMenuItem.setText("Eliminar");
        eliminarProductoCarritoMenuItem.addActionListener(this::eliminarProductoCarritoMenuItemActionPerformed);
        carritoMenu.add(eliminarProductoCarritoMenuItem);

        menuBar.add(carritoMenu);

        idiomaMenu.setText("Idioma");

        idiomaEspanolMenuItem.setText("Español");
        idiomaEspanolMenuItem.addActionListener(this::idiomaEspanolMenuItemActionPerformed);
        idiomaMenu.add(idiomaEspanolMenuItem);

        idiomaInglesMenuItem.setText("Ingles");
        idiomaInglesMenuItem.addActionListener(this::idiomaInglesMenuItemActionPerformed);
        idiomaMenu.add(idiomaInglesMenuItem);

        menuBar.add(idiomaMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProductoMenuItemActionPerformed
        if (!actualizarProductoView.isVisible()) {
            desktopPane.remove(actualizarProductoView);
            actualizarProductoView.setVisible(true);
            desktopPane.add(actualizarProductoView);
        }
    }//GEN-LAST:event_actualizarProductoMenuItemActionPerformed

    private void crearProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoMenuItemActionPerformed
        if(!crearProductoView.isVisible()){
            desktopPane.remove(crearProductoView);
            crearProductoView.setVisible(true);
            desktopPane.add(crearProductoView);
        }
    }//GEN-LAST:event_crearProductoMenuItemActionPerformed

    private void buscarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoMenuItemActionPerformed
        if (!buscarProductoView.isVisible()) {
            desktopPane.remove(buscarProductoView);
            buscarProductoView.setVisible(true);
            desktopPane.add(buscarProductoView);
        }
    }//GEN-LAST:event_buscarProductoMenuItemActionPerformed

    private void eliminarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoMenuItemActionPerformed
        if (!eliminarProductoView.isVisible()) {
            desktopPane.remove(eliminarProductoView);
            eliminarProductoView.setVisible(true);
            desktopPane.add(eliminarProductoView);
        }
    }//GEN-LAST:event_eliminarProductoMenuItemActionPerformed

    private void listarProductosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProductosMenuItemActionPerformed
        if (!listarProductosView.isVisible()) {
            desktopPane.remove(listarProductosView);
            listarProductosView.setVisible(true);
            desktopPane.add(listarProductosView);
        }
    }//GEN-LAST:event_listarProductosMenuItemActionPerformed

    private void idiomaEspanolMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomaEspanolMenuItemActionPerformed
        Locale locale = new Locale("es", "EC");
        cambiarIdioma(locale);
        crearProductoView.cambiarIdioma(locale);
    }//GEN-LAST:event_idiomaEspanolMenuItemActionPerformed

    private void eliminarProductoCarritoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoCarritoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarProductoCarritoMenuItemActionPerformed

    private void idiomaInglesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomaInglesMenuItemActionPerformed
        Locale locale = new Locale("en", "US");
        cambiarIdioma(locale);
        crearProductoView.cambiarIdioma(locale);
    }//GEN-LAST:event_idiomaInglesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actualizarProductoMenuItem;
    private javax.swing.JMenuItem agregarProductoCarritoMenuItem;
    private javax.swing.JMenuItem buscarProductoMenuItem;
    private javax.swing.JMenu carritoMenu;
    private javax.swing.JMenuItem crearProductoMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem eliminarProductoCarritoMenuItem;
    private javax.swing.JMenuItem eliminarProductoMenuItem;
    private javax.swing.JMenuItem idiomaEspanolMenuItem;
    private javax.swing.JMenuItem idiomaInglesMenuItem;
    private javax.swing.JMenu idiomaMenu;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JMenuItem listarProductosMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu productoMenu;
    // End of variables declaration//GEN-END:variables

}
